
package br.tezza.wsclientVenda;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "VendaJaxWS", targetNamespace = "http://jaxWS.tezza.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface VendaJaxWS {


    /**
     * 
     * @return
     *     returns br.tezza.wsclientVenda.PojoVenda
     * @throws ServletException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "resultadoVenda", targetNamespace = "")
    @RequestWrapper(localName = "enviarVenda", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientVenda.EnviarVenda")
    @ResponseWrapper(localName = "enviarVendaResponse", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientVenda.EnviarVendaResponse")
    public PojoVenda enviarVenda()
        throws IOException_Exception, ServletException_Exception
    ;

}
