
package br.tezza.wsclientEntrega;

import javax.jws.WebMethod;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "EntregaJaxWS", targetNamespace = "http://jaxWS.tezza.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface EntregaJaxWS {


    /**
     * 
     * @return
     *     returns br.tezza.wsclientEntrega.PojoEntrega
     * @throws ServletException_Exception
     * @throws IOException_Exception
     */
    @WebMethod
    @WebResult(name = "resultadoEntrega", targetNamespace = "")
    @RequestWrapper(localName = "enviarEntrega", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientEntrega.EnviarEntrega")
    @ResponseWrapper(localName = "enviarEntregaResponse", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientEntrega.EnviarEntregaResponse")
    public PojoEntrega enviarEntrega()
        throws IOException_Exception, ServletException_Exception
    ;

}
