
package br.tezza.wsclientProduto;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "ProdutoWS", targetNamespace = "http://jaxWS.tezza.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ProdutoWS {


    /**
     * 
     * @return
     *     returns java.util.List<br.tezza.wsclientProduto.Produto>
     */
    @WebMethod
    @WebResult(name = "resultadoListarTodos", targetNamespace = "")
    @RequestWrapper(localName = "listarTodos", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.ListarTodos")
    @ResponseWrapper(localName = "listarTodosResponse", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.ListarTodosResponse")
    public List<Produto> listarTodos();

    /**
     * 
     * @param paramProduto
     */
    @WebMethod
    @RequestWrapper(localName = "atualizar", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.Atualizar")
    @ResponseWrapper(localName = "atualizarResponse", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.AtualizarResponse")
    public void atualizar(
        @WebParam(name = "paramProduto", targetNamespace = "")
        Produto paramProduto);

    /**
     * 
     * @param paramProduto
     */
    @WebMethod
    @RequestWrapper(localName = "gravar", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.Gravar")
    @ResponseWrapper(localName = "gravarResponse", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.GravarResponse")
    public void gravar(
        @WebParam(name = "paramProduto", targetNamespace = "")
        Produto paramProduto);

    /**
     * 
     * @param paramId
     */
    @WebMethod
    @RequestWrapper(localName = "excluir", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.Excluir")
    @ResponseWrapper(localName = "excluirResponse", targetNamespace = "http://jaxWS.tezza.br/", className = "br.tezza.wsclientProduto.ExcluirResponse")
    public void excluir(
        @WebParam(name = "paramId", targetNamespace = "")
        Long paramId);

}
